pull_request_rules:
  - name: label conflicts
    conditions:
      - conflict
    actions:
      label:
        toggle:
          - conflict

  - name: Automatic merge on approval
    conditions:
      - '#commits-behind=0'
      - or:
          - '#approved-reviews-by>=1'
          - label=ci:auto-merge
      - not:
          and:
            - 'head~=renovate/lockfile-maintenance-.*'
            - 'created-at>24h ago'
      - base=master
      - check-success=python-tests
      - check-success=build-wheel
      - check-success=pre-commit
      - check-success=cargo-lint-test
      - check-success=autofix
    actions:
      merge:
        method: squash
