import builtins
import typing
from typing import TypeAlias

__all__ = [
    "Amount",
    "Balance",
    "Close",
    "Comment",
    "Commodity",
    "CostAmount",
    "CostSpec",
    "Custom",
    "CustomValue",
    "Directive",
    "Document",
    "Event",
    "File",
    "Headline",
    "Include",
    "KeyValue",
    "KeyValueValue",
    "Meta",
    "Note",
    "NumberExpr",
    "Open",
    "Option",
    "Pad",
    "Plugin",
    "PopMeta",
    "Posting",
    "Price",
    "PushMeta",
    "Query",
    "Span",
    "SpannedBinaryOp",
    "SpannedBool",
    "SpannedKeyValueValue",
    "SpannedPriceOperator",
    "SpannedStr",
    "Tag",
    "Transaction",
    "parse_file",
    "parse_string",
]

Directive: TypeAlias = (
    Open
    | Close
    | Balance
    | Pad
    | Transaction
    | Commodity
    | Price
    | Event
    | Query
    | Note
    | Document
    | Custom
    | Option
    | Include
    | Plugin
    | Tag
    | PushMeta
    | PopMeta
    | Comment
    | Headline
)

@typing.final
class File:
    @property
    def filename(self) -> builtins.str: ...
    @property
    def content(self) -> builtins.str: ...
    @property
    def directives(self) -> builtins.list[Directive]: ...

@typing.final
class Amount:
    @property
    def raw(self) -> SpannedStr: ...
    @property
    def number(self) -> NumberExpr: ...
    @property
    def currency(self) -> typing.Optional[SpannedStr]: ...
    def dump(self) -> builtins.str: ...

@typing.final
class Balance:
    @property
    def meta(self) -> Meta: ...
    @property
    def span(self) -> Span: ...
    @property
    def file(self) -> File: ...
    @property
    def date(self) -> SpannedStr: ...
    @property
    def account(self) -> SpannedStr: ...
    @property
    def amount(self) -> Amount: ...
    @property
    def tolerance(self) -> typing.Optional[SpannedStr]: ...
    @property
    def comment(self) -> typing.Optional[SpannedStr]: ...
    @property
    def key_values(self) -> builtins.list[KeyValue]: ...
    def dump(self) -> builtins.str: ...

@typing.final
class Close:
    @property
    def meta(self) -> Meta: ...
    @property
    def span(self) -> Span: ...
    @property
    def file(self) -> File: ...
    @property
    def date(self) -> SpannedStr: ...
    @property
    def account(self) -> SpannedStr: ...
    @property
    def comment(self) -> typing.Optional[SpannedStr]: ...
    @property
    def key_values(self) -> builtins.list[KeyValue]: ...
    def dump(self) -> builtins.str: ...

@typing.final
class Comment:
    @property
    def meta(self) -> Meta: ...
    @property
    def span(self) -> Span: ...
    @property
    def file(self) -> File: ...
    @property
    def text(self) -> SpannedStr: ...
    def dump(self) -> builtins.str: ...

@typing.final
class Commodity:
    @property
    def meta(self) -> Meta: ...
    @property
    def span(self) -> Span: ...
    @property
    def file(self) -> File: ...
    @property
    def date(self) -> SpannedStr: ...
    @property
    def currency(self) -> SpannedStr: ...
    @property
    def comment(self) -> typing.Optional[SpannedStr]: ...
    @property
    def key_values(self) -> builtins.list[KeyValue]: ...
    def dump(self) -> builtins.str: ...

@typing.final
class CostAmount:
    @property
    def per(self) -> typing.Optional[NumberExpr]: ...
    @property
    def total(self) -> typing.Optional[NumberExpr]: ...
    @property
    def currency(self) -> typing.Optional[SpannedStr]: ...

@typing.final
class CostSpec:
    @property
    def raw(self) -> SpannedStr: ...
    @property
    def amount(self) -> typing.Optional[CostAmount]: ...
    @property
    def date(self) -> typing.Optional[SpannedStr]: ...
    @property
    def label(self) -> typing.Optional[SpannedStr]: ...
    @property
    def merge(self) -> typing.Optional[SpannedBool]: ...
    @property
    def is_total(self) -> SpannedBool: ...
    def dump(self) -> builtins.str: ...

@typing.final
class Custom:
    @property
    def meta(self) -> Meta: ...
    @property
    def span(self) -> Span: ...
    @property
    def file(self) -> File: ...
    @property
    def date(self) -> SpannedStr: ...
    @property
    def name(self) -> SpannedStr: ...
    @property
    def values(self) -> builtins.list[CustomValue]: ...
    @property
    def comment(self) -> typing.Optional[SpannedStr]: ...
    @property
    def key_values(self) -> builtins.list[KeyValue]: ...
    def dump(self) -> builtins.str: ...

@typing.final
class CustomValue:
    @property
    def raw(self) -> SpannedStr: ...
    @property
    def kind(self) -> builtins.str: ...
    @property
    def number(self) -> typing.Optional[NumberExpr]: ...
    @property
    def amount(self) -> typing.Optional[Amount]: ...
    def dump(self) -> builtins.str: ...

@typing.final
class Document:
    @property
    def meta(self) -> Meta: ...
    @property
    def span(self) -> Span: ...
    @property
    def file(self) -> File: ...
    @property
    def date(self) -> SpannedStr: ...
    @property
    def account(self) -> SpannedStr: ...
    @property
    def filename(self) -> SpannedStr: ...
    @property
    def tags_links(self) -> typing.Optional[SpannedStr]: ...
    @property
    def tags(self) -> builtins.list[SpannedStr]: ...
    @property
    def links(self) -> builtins.list[SpannedStr]: ...
    @property
    def comment(self) -> typing.Optional[SpannedStr]: ...
    @property
    def key_values(self) -> builtins.list[KeyValue]: ...
    def dump(self) -> builtins.str: ...

@typing.final
class Event:
    @property
    def meta(self) -> Meta: ...
    @property
    def span(self) -> Span: ...
    @property
    def file(self) -> File: ...
    @property
    def date(self) -> SpannedStr: ...
    @property
    def event_type(self) -> SpannedStr: ...
    @property
    def desc(self) -> SpannedStr: ...
    @property
    def comment(self) -> typing.Optional[SpannedStr]: ...
    @property
    def key_values(self) -> builtins.list[KeyValue]: ...
    def dump(self) -> builtins.str: ...

@typing.final
class Headline:
    @property
    def meta(self) -> Meta: ...
    @property
    def span(self) -> Span: ...
    @property
    def file(self) -> File: ...
    @property
    def text(self) -> SpannedStr: ...
    def dump(self) -> builtins.str: ...

@typing.final
class Include:
    @property
    def meta(self) -> Meta: ...
    @property
    def span(self) -> Span: ...
    @property
    def file(self) -> File: ...
    @property
    def filename(self) -> SpannedStr: ...
    def dump(self) -> builtins.str: ...

@typing.final
class KeyValue:
    @property
    def meta(self) -> Meta: ...
    @property
    def span(self) -> Span: ...
    @property
    def file(self) -> File: ...
    @property
    def key(self) -> SpannedStr: ...
    @property
    def value(self) -> typing.Optional[SpannedKeyValueValue]: ...
    def dump(self) -> builtins.str: ...

@typing.final
class KeyValueValue:
    @property
    def kind(self) -> builtins.str: ...
    @property
    def string(self) -> typing.Optional[builtins.str]: ...
    @property
    def boolean(self) -> typing.Optional[builtins.bool]: ...

@typing.final
class Meta:
    @property
    def filename(self) -> builtins.str: ...
    @property
    def line(self) -> builtins.int: ...
    @property
    def column(self) -> builtins.int: ...

@typing.final
class Note:
    @property
    def meta(self) -> Meta: ...
    @property
    def span(self) -> Span: ...
    @property
    def file(self) -> File: ...
    @property
    def date(self) -> SpannedStr: ...
    @property
    def account(self) -> SpannedStr: ...
    @property
    def note(self) -> SpannedStr: ...
    @property
    def comment(self) -> typing.Optional[SpannedStr]: ...
    @property
    def key_values(self) -> builtins.list[KeyValue]: ...
    def dump(self) -> builtins.str: ...

@typing.final
class NumberExpr:
    @property
    def kind(self) -> builtins.str: ...
    @property
    def span(self) -> Span: ...
    @property
    def file(self) -> File: ...
    @property
    def literal(self) -> typing.Optional[SpannedStr]: ...
    @property
    def left(self) -> typing.Optional[NumberExpr]: ...
    @property
    def op(self) -> typing.Optional[SpannedBinaryOp]: ...
    @property
    def right(self) -> typing.Optional[NumberExpr]: ...
    def dump(self) -> builtins.str: ...

@typing.final
class Open:
    @property
    def meta(self) -> Meta: ...
    @property
    def span(self) -> Span: ...
    @property
    def file(self) -> File: ...
    @property
    def date(self) -> SpannedStr: ...
    @property
    def account(self) -> SpannedStr: ...
    @property
    def currencies(self) -> builtins.list[SpannedStr]: ...
    @property
    def opt_booking(self) -> typing.Optional[SpannedStr]: ...
    @property
    def comment(self) -> typing.Optional[SpannedStr]: ...
    @property
    def key_values(self) -> builtins.list[KeyValue]: ...
    def dump(self) -> builtins.str: ...

@typing.final
class Option:
    @property
    def meta(self) -> Meta: ...
    @property
    def span(self) -> Span: ...
    @property
    def file(self) -> File: ...
    @property
    def key(self) -> SpannedStr: ...
    @property
    def value(self) -> SpannedStr: ...
    def dump(self) -> builtins.str: ...

@typing.final
class Pad:
    @property
    def meta(self) -> Meta: ...
    @property
    def span(self) -> Span: ...
    @property
    def file(self) -> File: ...
    @property
    def date(self) -> SpannedStr: ...
    @property
    def account(self) -> SpannedStr: ...
    @property
    def from_account(self) -> SpannedStr: ...
    @property
    def comment(self) -> typing.Optional[SpannedStr]: ...
    @property
    def key_values(self) -> builtins.list[KeyValue]: ...
    def dump(self) -> builtins.str: ...

@typing.final
class Plugin:
    @property
    def meta(self) -> Meta: ...
    @property
    def span(self) -> Span: ...
    @property
    def file(self) -> File: ...
    @property
    def name(self) -> SpannedStr: ...
    @property
    def config(self) -> typing.Optional[SpannedStr]: ...
    def dump(self) -> builtins.str: ...

@typing.final
class PopMeta:
    @property
    def meta(self) -> Meta: ...
    @property
    def span(self) -> Span: ...
    @property
    def file(self) -> File: ...
    @property
    def key(self) -> SpannedStr: ...
    def dump(self) -> builtins.str: ...

@typing.final
class Posting:
    @property
    def meta(self) -> Meta: ...
    @property
    def span(self) -> Span: ...
    @property
    def file(self) -> File: ...
    @property
    def opt_flag(self) -> typing.Optional[SpannedStr]: ...
    @property
    def account(self) -> SpannedStr: ...
    @property
    def amount(self) -> typing.Optional[Amount]: ...
    @property
    def cost_spec(self) -> typing.Optional[CostSpec]: ...
    @property
    def price_operator(self) -> typing.Optional[SpannedPriceOperator]: ...
    @property
    def price_annotation(self) -> typing.Optional[Amount]: ...
    @property
    def comment(self) -> typing.Optional[SpannedStr]: ...
    @property
    def key_values(self) -> builtins.list[KeyValue]: ...
    def dump(self) -> builtins.str: ...

@typing.final
class Price:
    @property
    def meta(self) -> Meta: ...
    @property
    def span(self) -> Span: ...
    @property
    def file(self) -> File: ...
    @property
    def date(self) -> SpannedStr: ...
    @property
    def currency(self) -> SpannedStr: ...
    @property
    def amount(self) -> Amount: ...
    @property
    def comment(self) -> typing.Optional[SpannedStr]: ...
    @property
    def key_values(self) -> builtins.list[KeyValue]: ...
    def dump(self) -> builtins.str: ...

@typing.final
class PushMeta:
    @property
    def meta(self) -> Meta: ...
    @property
    def span(self) -> Span: ...
    @property
    def file(self) -> File: ...
    @property
    def key(self) -> SpannedStr: ...
    @property
    def value(self) -> typing.Optional[SpannedKeyValueValue]: ...
    def dump(self) -> builtins.str: ...

@typing.final
class Query:
    @property
    def meta(self) -> Meta: ...
    @property
    def span(self) -> Span: ...
    @property
    def file(self) -> File: ...
    @property
    def date(self) -> SpannedStr: ...
    @property
    def name(self) -> SpannedStr: ...
    @property
    def query(self) -> SpannedStr: ...
    @property
    def comment(self) -> typing.Optional[SpannedStr]: ...
    @property
    def key_values(self) -> builtins.list[KeyValue]: ...
    def dump(self) -> builtins.str: ...

@typing.final
class Span:
    @property
    def start(self) -> builtins.int: ...
    @property
    def end(self) -> builtins.int: ...

@typing.final
class SpannedBinaryOp:
    @property
    def span(self) -> Span: ...
    @property
    def file(self) -> File: ...
    @property
    def content(self) -> builtins.str: ...
    def dump(self) -> builtins.str: ...

@typing.final
class SpannedBool:
    @property
    def span(self) -> Span: ...
    @property
    def file(self) -> File: ...
    @property
    def content(self) -> builtins.bool: ...
    def dump(self) -> builtins.str: ...

@typing.final
class SpannedKeyValueValue:
    @property
    def span(self) -> Span: ...
    @property
    def file(self) -> File: ...
    @property
    def content(self) -> KeyValueValue: ...
    def dump(self) -> builtins.str: ...

@typing.final
class SpannedPriceOperator:
    @property
    def span(self) -> Span: ...
    @property
    def file(self) -> File: ...
    @property
    def content(self) -> builtins.str: ...
    def dump(self) -> builtins.str: ...

@typing.final
class SpannedStr:
    @property
    def span(self) -> Span: ...
    @property
    def file(self) -> File: ...
    @property
    def content(self) -> builtins.str: ...
    def dump(self) -> builtins.str: ...

@typing.final
class Tag:
    @property
    def meta(self) -> Meta: ...
    @property
    def span(self) -> Span: ...
    @property
    def file(self) -> File: ...
    @property
    def tag(self) -> SpannedStr: ...
    @property
    def action(self) -> builtins.str: ...
    def dump(self) -> builtins.str: ...

@typing.final
class Transaction:
    @property
    def meta(self) -> Meta: ...
    @property
    def span(self) -> Span: ...
    @property
    def file(self) -> File: ...
    @property
    def date(self) -> SpannedStr: ...
    @property
    def txn(self) -> typing.Optional[SpannedStr]: ...
    @property
    def payee(self) -> typing.Optional[SpannedStr]: ...
    @property
    def narration(self) -> typing.Optional[SpannedStr]: ...
    @property
    def tags_links(self) -> typing.Optional[SpannedStr]: ...
    @property
    def tags(self) -> builtins.list[SpannedStr]: ...
    @property
    def links(self) -> builtins.list[SpannedStr]: ...
    @property
    def comment(self) -> typing.Optional[SpannedStr]: ...
    @property
    def tags_links_lines(self) -> builtins.list[SpannedStr]: ...
    @property
    def comments(self) -> builtins.list[SpannedStr]: ...
    @property
    def key_values(self) -> builtins.list[KeyValue]: ...
    @property
    def postings(self) -> builtins.list[Posting]: ...
    def dump(self) -> builtins.str: ...

def parse_file(filename: builtins.str) -> File: ...
def parse_string(
    content: builtins.str, filename: builtins.str = "<string>"
) -> File: ...
