import typing

from ._directive import Directive

__all__ = [
    "Amount",
    "Balance",
    "Close",
    "Comment",
    "Commodity",
    "CostAmount",
    "CostSpec",
    "Custom",
    "CustomValue",
    "Directive",
    "Document",
    "Event",
    "File",
    "Headline",
    "Include",
    "KeyValue",
    "KeyValueValue",
    "Note",
    "NumberExpr",
    "Open",
    "Option",
    "Pad",
    "Plugin",
    "PopMeta",
    "Posting",
    "Price",
    "PushMeta",
    "Query",
    "Span",
    "SpannedBinaryOp",
    "SpannedBool",
    "SpannedKeyValueValue",
    "SpannedPriceOperator",
    "SpannedStr",
    "Tag",
    "Transaction",
    "parse_file",
    "parse_string",
]

@typing.final
class File:
    @property
    def filename(self) -> str: ...
    @property
    def content(self) -> str: ...
    @property
    def directives(self) -> list[Directive]: ...

@typing.final
class Amount:
    @property
    def raw(self) -> SpannedStr: ...
    @property
    def number(self) -> NumberExpr: ...
    @property
    def currency(self) -> SpannedStr | None: ...
    def dump(self) -> str: ...

@typing.final
class Balance(Directive):
    @property
    def span(self) -> Span: ...
    @property
    def file(self) -> File: ...
    @property
    def date(self) -> SpannedStr: ...
    @property
    def account(self) -> SpannedStr: ...
    @property
    def amount(self) -> Amount: ...
    @property
    def tolerance(self) -> SpannedStr | None: ...
    @property
    def comment(self) -> SpannedStr | None: ...
    @property
    def key_values(self) -> list[KeyValue]: ...
    def dump(self) -> str: ...

@typing.final
class Close(Directive):
    @property
    def span(self) -> Span: ...
    @property
    def file(self) -> File: ...
    @property
    def date(self) -> SpannedStr: ...
    @property
    def account(self) -> SpannedStr: ...
    @property
    def comment(self) -> SpannedStr | None: ...
    @property
    def key_values(self) -> list[KeyValue]: ...
    def dump(self) -> str: ...

@typing.final
class Comment(Directive):
    @property
    def span(self) -> Span: ...
    @property
    def file(self) -> File: ...
    @property
    def text(self) -> SpannedStr: ...
    def dump(self) -> str: ...

@typing.final
class Commodity(Directive):
    @property
    def span(self) -> Span: ...
    @property
    def file(self) -> File: ...
    @property
    def date(self) -> SpannedStr: ...
    @property
    def currency(self) -> SpannedStr: ...
    @property
    def comment(self) -> SpannedStr | None: ...
    @property
    def key_values(self) -> list[KeyValue]: ...
    def dump(self) -> str: ...

@typing.final
class CostAmount:
    @property
    def per(self) -> NumberExpr | None: ...
    @property
    def total(self) -> NumberExpr | None: ...
    @property
    def currency(self) -> SpannedStr | None: ...

@typing.final
class CostSpec:
    @property
    def raw(self) -> SpannedStr: ...
    @property
    def amount(self) -> CostAmount | None: ...
    @property
    def date(self) -> SpannedStr | None: ...
    @property
    def label(self) -> SpannedStr | None: ...
    @property
    def merge(self) -> SpannedBool | None: ...
    @property
    def is_total(self) -> SpannedBool: ...
    def dump(self) -> str: ...

@typing.final
class Custom(Directive):
    @property
    def span(self) -> Span: ...
    @property
    def file(self) -> File: ...
    @property
    def date(self) -> SpannedStr: ...
    @property
    def name(self) -> SpannedStr: ...
    @property
    def values(self) -> list[CustomValue]: ...
    @property
    def comment(self) -> SpannedStr | None: ...
    @property
    def key_values(self) -> list[KeyValue]: ...
    def dump(self) -> str: ...

@typing.final
class CustomValue:
    @property
    def raw(self) -> SpannedStr: ...
    @property
    def kind(self) -> str: ...
    @property
    def number(self) -> NumberExpr | None: ...
    @property
    def amount(self) -> Amount | None: ...
    def dump(self) -> str: ...

@typing.final
class Document(Directive):
    @property
    def span(self) -> Span: ...
    @property
    def file(self) -> File: ...
    @property
    def date(self) -> SpannedStr: ...
    @property
    def account(self) -> SpannedStr: ...
    @property
    def filename(self) -> SpannedStr: ...
    @property
    def tags_links(self) -> SpannedStr | None: ...
    @property
    def tags(self) -> list[SpannedStr]: ...
    @property
    def links(self) -> list[SpannedStr]: ...
    @property
    def comment(self) -> SpannedStr | None: ...
    @property
    def key_values(self) -> list[KeyValue]: ...
    def dump(self) -> str: ...

@typing.final
class Event(Directive):
    @property
    def span(self) -> Span: ...
    @property
    def file(self) -> File: ...
    @property
    def date(self) -> SpannedStr: ...
    @property
    def event_type(self) -> SpannedStr: ...
    @property
    def desc(self) -> SpannedStr: ...
    @property
    def comment(self) -> SpannedStr | None: ...
    @property
    def key_values(self) -> list[KeyValue]: ...
    def dump(self) -> str: ...

@typing.final
class Headline(Directive):
    @property
    def span(self) -> Span: ...
    @property
    def file(self) -> File: ...
    @property
    def text(self) -> SpannedStr: ...
    def dump(self) -> str: ...

@typing.final
class Include(Directive):
    @property
    def span(self) -> Span: ...
    @property
    def file(self) -> File: ...
    @property
    def filename(self) -> SpannedStr: ...
    def dump(self) -> str: ...

@typing.final
class KeyValue:
    @property
    def span(self) -> Span: ...
    @property
    def file(self) -> File: ...
    @property
    def key(self) -> SpannedStr: ...
    @property
    def value(self) -> SpannedKeyValueValue | None: ...
    def dump(self) -> str: ...

@typing.final
class KeyValueValue:
    @property
    def kind(self) -> str: ...
    @property
    def string(self) -> str | None: ...
    @property
    def boolean(self) -> bool | None: ...

@typing.final
@typing.final
class Note(Directive):
    @property
    def span(self) -> Span: ...
    @property
    def file(self) -> File: ...
    @property
    def date(self) -> SpannedStr: ...
    @property
    def account(self) -> SpannedStr: ...
    @property
    def note(self) -> SpannedStr: ...
    @property
    def comment(self) -> SpannedStr | None: ...
    @property
    def key_values(self) -> list[KeyValue]: ...
    def dump(self) -> str: ...

@typing.final
class NumberExpr:
    @property
    def kind(self) -> str: ...
    @property
    def span(self) -> Span: ...
    @property
    def file(self) -> File: ...
    @property
    def literal(self) -> SpannedStr | None: ...
    @property
    def left(self) -> NumberExpr | None: ...
    @property
    def op(self) -> SpannedBinaryOp | None: ...
    @property
    def right(self) -> NumberExpr | None: ...
    def dump(self) -> str: ...

@typing.final
class Open(Directive):
    @property
    def span(self) -> Span: ...
    @property
    def file(self) -> File: ...
    @property
    def date(self) -> SpannedStr: ...
    @property
    def account(self) -> SpannedStr: ...
    @property
    def currencies(self) -> list[SpannedStr]: ...
    @property
    def opt_booking(self) -> SpannedStr | None: ...
    @property
    def comment(self) -> SpannedStr | None: ...
    @property
    def key_values(self) -> list[KeyValue]: ...
    def dump(self) -> str: ...

@typing.final
class Option(Directive):
    @property
    def span(self) -> Span: ...
    @property
    def file(self) -> File: ...
    @property
    def key(self) -> SpannedStr: ...
    @property
    def value(self) -> SpannedStr: ...
    def dump(self) -> str: ...

@typing.final
class Pad(Directive):
    @property
    def span(self) -> Span: ...
    @property
    def file(self) -> File: ...
    @property
    def date(self) -> SpannedStr: ...
    @property
    def account(self) -> SpannedStr: ...
    @property
    def from_account(self) -> SpannedStr: ...
    @property
    def comment(self) -> SpannedStr | None: ...
    @property
    def key_values(self) -> list[KeyValue]: ...
    def dump(self) -> str: ...

@typing.final
class Plugin(Directive):
    @property
    def span(self) -> Span: ...
    @property
    def file(self) -> File: ...
    @property
    def name(self) -> SpannedStr: ...
    @property
    def config(self) -> SpannedStr | None: ...
    def dump(self) -> str: ...

@typing.final
class PopMeta(Directive):
    @property
    def span(self) -> Span: ...
    @property
    def file(self) -> File: ...
    @property
    def key(self) -> SpannedStr: ...
    def dump(self) -> str: ...

@typing.final
class Posting:
    @property
    def span(self) -> Span: ...
    @property
    def file(self) -> File: ...
    @property
    def opt_flag(self) -> SpannedStr | None: ...
    @property
    def account(self) -> SpannedStr: ...
    @property
    def amount(self) -> Amount | None: ...
    @property
    def cost_spec(self) -> CostSpec | None: ...
    @property
    def price_operator(self) -> SpannedPriceOperator | None: ...
    @property
    def price_annotation(self) -> Amount | None: ...
    @property
    def comment(self) -> SpannedStr | None: ...
    @property
    def key_values(self) -> list[KeyValue]: ...
    def dump(self) -> str: ...

@typing.final
class Price(Directive):
    @property
    def span(self) -> Span: ...
    @property
    def file(self) -> File: ...
    @property
    def date(self) -> SpannedStr: ...
    @property
    def currency(self) -> SpannedStr: ...
    @property
    def amount(self) -> Amount: ...
    @property
    def comment(self) -> SpannedStr | None: ...
    @property
    def key_values(self) -> list[KeyValue]: ...
    def dump(self) -> str: ...

@typing.final
class PushMeta(Directive):
    @property
    def span(self) -> Span: ...
    @property
    def file(self) -> File: ...
    @property
    def key(self) -> SpannedStr: ...
    @property
    def value(self) -> SpannedKeyValueValue | None: ...
    def dump(self) -> str: ...

@typing.final
class Query(Directive):
    @property
    def span(self) -> Span: ...
    @property
    def file(self) -> File: ...
    @property
    def date(self) -> SpannedStr: ...
    @property
    def name(self) -> SpannedStr: ...
    @property
    def query(self) -> SpannedStr: ...
    @property
    def comment(self) -> SpannedStr | None: ...
    @property
    def key_values(self) -> list[KeyValue]: ...
    def dump(self) -> str: ...

@typing.final
class Span:
    @property
    def start(self) -> int: ...
    @property
    def end(self) -> int: ...

@typing.final
class SpannedBinaryOp:
    @property
    def span(self) -> Span: ...
    @property
    def file(self) -> File: ...
    @property
    def content(self) -> str: ...
    def dump(self) -> str: ...

@typing.final
class SpannedBool:
    @property
    def span(self) -> Span: ...
    @property
    def file(self) -> File: ...
    @property
    def content(self) -> bool: ...
    def dump(self) -> str: ...

@typing.final
class SpannedKeyValueValue:
    @property
    def span(self) -> Span: ...
    @property
    def file(self) -> File: ...
    @property
    def content(self) -> KeyValueValue: ...
    def dump(self) -> str: ...

@typing.final
class SpannedPriceOperator:
    @property
    def span(self) -> Span: ...
    @property
    def file(self) -> File: ...
    @property
    def content(self) -> str: ...
    def dump(self) -> str: ...

@typing.final
class SpannedStr:
    @property
    def span(self) -> Span: ...
    @property
    def file(self) -> File: ...
    @property
    def content(self) -> str: ...
    def dump(self) -> str: ...

@typing.final
class Tag(Directive):
    @property
    def span(self) -> Span: ...
    @property
    def file(self) -> File: ...
    @property
    def tag(self) -> SpannedStr: ...
    @property
    def action(self) -> str: ...
    def dump(self) -> str: ...

@typing.final
class Transaction(Directive):
    @property
    def span(self) -> Span: ...
    @property
    def file(self) -> File: ...
    @property
    def date(self) -> SpannedStr: ...
    @property
    def txn(self) -> SpannedStr | None: ...
    @property
    def payee(self) -> SpannedStr | None: ...
    @property
    def narration(self) -> SpannedStr | None: ...
    @property
    def tags_links(self) -> SpannedStr | None: ...
    @property
    def tags(self) -> list[SpannedStr]: ...
    @property
    def links(self) -> list[SpannedStr]: ...
    @property
    def comment(self) -> SpannedStr | None: ...
    @property
    def tags_links_lines(self) -> list[SpannedStr]: ...
    @property
    def comments(self) -> list[SpannedStr]: ...
    @property
    def key_values(self) -> list[KeyValue]: ...
    @property
    def postings(self) -> list[Posting]: ...
    def dump(self) -> str: ...

def parse_file(filename: str) -> File: ...
def parse_string(content: str, filename: str = "<string>") -> File: ...
